# Docker Compose Override for Local Development
# This file is automatically used by docker-compose for local development
# It overrides the production settings in docker-compose.yml

version: '3.9'

services:
  voting-app:
    environment:
      FLASK_ENV: development
      APP_URL: http://localhost:5000
      CORS_ORIGINS: "*"
    ports:
      - "5000:5000"
    networks:
      - local
    labels: []  # Remove all Traefik labels for local development

  pgadmin:
    ports:
      - "8080:80"
    networks:
      - local
    labels: []  # Remove all Traefik labels for local development
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

networks:
  proxy:
    external: false  # Don't require external proxy network for local dev
