# File: .github/workflows/build-and-publish-ghcr.yml
name: Build & Publish to GHCR

on:
  push:
    branches: [main]          # build on every push to main
  pull_request:               # test PRs, but skip the push step
  workflow_dispatch:          # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    # Required so the job can upload images to the registry
    permissions:
      contents: read          # checkout code
      packages: write         # push to ghcr.io

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      # Optional: speed-ups for multi-arch or cache;
      # harmless even for simple single-arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile          # the Dockerfile you provided
          push: ${{ github.event_name != 'pull_request' }}  # skip pushing on PRs
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
          cache-from: type=gha         # enable GitHub-hosted build cache
          cache-to: type=gha,mode=max
